# HTTP 服务器配置
http_server:
  port: 8080
  access_key: "test123"   # 登录密钥，请修改为安全的密钥

subscription:
  key: "your-key" #需要设置节点订阅密钥 最终访问链接http://你的ip或域名/api/subscription?key=填入这个key

# 定时任务配置
schedule:
  cron: "0 */6 * * *"  # 每6小时执行一次

# Clash 配置（容器内部使用）
clash:
  api_url: "http://127.0.0.1:9090"  # Clash API地址（容器内部）
  secret: ""                        # Clash API密钥
  proxy:
    auth: false                     # 是否需要代理认证 如果设置为true，需要设置用户和密码
    user: ""                        # 代理用户名
    pass: ""                        # 代理密码
    host: "127.0.0.1"              # 代理地址（容器内部）
    port: 7890                      # 代理端口（容器内部）
  external-controller: "127.0.0.1:9090" #默认只允许本机管理，如果想在外部管理设置为0.0.0.0:9090，此时建议设置clash.secret
  auto_close: false #执行完任务是否关闭clash
  allow-lan: false # 局域网访问代理开关

# Netflix 测试配置
netflix:
  # 测试用的Netflix URL列表
  test_urls:
    - "https://www.netflix.com/title/70143836"  # 绝命毒师
    - "https://www.netflix.com/title/81280792"  # 乐高

  error_msg: "Oh no!"              # Netflix显示的错误信息（检测代理）
  timeout: 20                      # 请求超时时间（秒）

  # 请求头设置
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
  accept_language: "zh-CN,zh;q=0.9,en;q=0.8"

# 代理配置文件 URL 列表
# 支持多个订阅源，会自动合并所有代理
proxy_config_urls:
  - "https://example.com/proxy1.yaml"  # 代理订阅地址1
  - "https://example.com/proxy2.yaml"  # 代理订阅地址2
  # - "https://example.com/proxy3.yaml"  # 可以添加更多订阅